/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Recorder, RecorderInterface } from "../../src/Recorder";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "standardizedKey",
        type: "bytes32",
      },
    ],
    name: "getDepositDelta",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "depositor",
                type: "address",
              },
              {
                internalType: "address",
                name: "asset",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amountAfterDeposit",
                type: "uint256",
              },
            ],
            internalType: "struct Recorder.UserInfo",
            name: "info",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "uniqueDeposits",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "currentDeposit",
            type: "uint256",
          },
        ],
        internalType: "struct Recorder.DepositInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "userHasDeposited",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Recorder__factory {
  static readonly abi = _abi;
  static createInterface(): RecorderInterface {
    return new Interface(_abi) as RecorderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Recorder {
    return new Contract(address, _abi, runner) as unknown as Recorder;
  }
}
