/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IMain, IMainInterface } from "../../../src/interfaces/IMain";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "ethSent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deposit",
        type: "uint256",
      },
    ],
    name: "ETHSentLessThanDeposit",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leaf",
        type: "bytes32",
      },
    ],
    name: "KeyAlreadyUsed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nullifier",
        type: "uint256",
      },
    ],
    name: "NullifierUsed",
    type: "error",
  },
  {
    inputs: [],
    name: "ProofNotVerified",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
    ],
    name: "RootNotInHistory",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "withdrawal",
        type: "uint256",
      },
    ],
    name: "WithdrawalExceedsMax",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "leaf",
        type: "bytes32",
      },
    ],
    name: "DepositAdded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "depositKey",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "standardizedKey",
        type: "bytes32",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "withdrawalKey",
        type: "bytes",
      },
      {
        internalType: "uint256[2]",
        name: "pA",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "pB",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "pC",
        type: "uint256[2]",
      },
      {
        internalType: "uint256",
        name: "nullifier",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMain__factory {
  static readonly abi = _abi;
  static createInterface(): IMainInterface {
    return new Interface(_abi) as IMainInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMain {
    return new Contract(address, _abi, runner) as unknown as IMain;
  }
}
