/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMainInterface extends Interface {
  getFunction(nameOrSignature: "deposit" | "withdraw"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DepositAdded"): EventFragment;

  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      BytesLike,
      BytesLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositAddedEvent {
  export type InputTuple = [leaf: BytesLike];
  export type OutputTuple = [leaf: string];
  export interface OutputObject {
    leaf: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMain extends BaseContract {
  connect(runner?: ContractRunner | null): IMain;
  waitForDeployment(): Promise<this>;

  interface: IMainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<[depositKey: BytesLike], [void], "payable">;

  withdraw: TypedContractMethod<
    [
      root: BytesLike,
      withdrawalKey: BytesLike,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      nullifier: BigNumberish,
      receipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[depositKey: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      root: BytesLike,
      withdrawalKey: BytesLike,
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish],
      nullifier: BigNumberish,
      receipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DepositAdded"
  ): TypedContractEvent<
    DepositAddedEvent.InputTuple,
    DepositAddedEvent.OutputTuple,
    DepositAddedEvent.OutputObject
  >;

  filters: {
    "DepositAdded(bytes32)": TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
    DepositAdded: TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
  };
}
